# Generated by Django 5.0.3 on 2024-05-03 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receta', '0002_medicamentos_enfermedadmedicamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfermedadmedicamento',
            name='IdEnfermedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Receta.enfermedades'),
        ),
        migrations.AlterField(
            model_name='enfermedadmedicamento',
            name='IdMedicamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Receta.medicamentos'),
        ),
    ]
