# Generated by Django 5.0.3 on 2024-05-04 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receta', '0003_alter_enfermedadmedicamento_idenfermedad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cNombre', models.CharField(max_length=30)),
                ('bEstatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Condiciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cNombre', models.CharField(max_length=30)),
                ('bEstatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cNombre', models.CharField(max_length=30)),
                ('bEstatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='enfermedadmedicamento',
            name='IdEnfermedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Receta.enfermedades'),
        ),
        migrations.AlterField(
            model_name='enfermedadmedicamento',
            name='IdMedicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Receta.medicamentos'),
        ),
        migrations.AlterField(
            model_name='enfermedadmedicamento',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='AlergiaMedicamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('IdMedicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Receta.medicamentos')),
                ('IdAlergia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Receta.alergias')),
            ],
        ),
        migrations.CreateModel(
            name='CondicionMedicamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('IdCondicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Receta.condiciones')),
                ('IdMedicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Receta.medicamentos')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumoMedicamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('IdMedicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Receta.medicamentos')),
                ('IdConsumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Receta.consumos')),
            ],
        ),
    ]
